#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : astral
Version  : 1.7.1
Release  : 4
URL      : https://files.pythonhosted.org/packages/c2/2c/9c885e6e0a7c5670a3ea30bdffa55e99016685b6d0a81fc31f4b09967145/astral-1.7.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c2/2c/9c885e6e0a7c5670a3ea30bdffa55e99016685b6d0a81fc31f4b09967145/astral-1.7.1.tar.gz
Summary  : Calculations for the position of the sun and moon.
Group    : Development/Tools
License  : Apache-2.0
Requires: astral-license = %{version}-%{release}
Requires: astral-python = %{version}-%{release}
Requires: astral-python3 = %{version}-%{release}
Requires: pytz
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-scons
BuildRequires : pytz

%description
======
        
        |travis_status| |pypi_ver|

%package license
Summary: license components for the astral package.
Group: Default

%description license
license components for the astral package.


%package python
Summary: python components for the astral package.
Group: Default
Requires: astral-python3 = %{version}-%{release}

%description python
python components for the astral package.


%package python3
Summary: python3 components for the astral package.
Group: Default
Requires: python3-core

%description python3
python3 components for the astral package.


%prep
%setup -q -n astral-1.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542311664
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/astral
cp LICENSE %{buildroot}/usr/share/package-licenses/astral/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/astral/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
